In [1]:
v = list(range(1, 6))
v
2 * v
import numpy as np
v = np.arange(1, 6)
v
2 * v

array([ 2,  4,  6,  8, 10])

In [2]:
x = [60, 70, 80, 90]
print(len(x))
print(x[0])
print(x[1])
print(x[-1])

4
60
70
90

In [5]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a * b
c

array([ 4, 10, 18])

In [6]:
import numpy as np
a = np.arange(15).reshape(3, 5)
print(a.shape)

(3, 5)

In [7]:
import numpy as np
a = np.array([
    [0,1,2,3],
    [10,11,12,13],
    [20,21,22,23],
])
print(a)
print(a.ndim)
print(a.shape)
print(a.dtype)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]]
2
(3, 4)
int64

In [8]:
import pandas as pd
from IPython.display import display
df = pd.DataFrame({"a": [4, 5, 6],
                   "b": [7, 8, 9],
                  "c": [10, 11, 12]},
                 index = [1, 2, 3])
display(df)
display(df['a'])

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

1    4
2    5
3    6
Name: a, dtype: int64

In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print('pandas imported')

pandas imported

In [10]:
dates = pd.date_range('20181001',periods=6)
dates

DatetimeIndex(['2018-10-01', '2018-10-02', '2018-10-03', '2018-10-04',
               '2018-10-05', '2018-10-06'],
              dtype='datetime64[ns]', freq='D')

In [11]:
df = pd.DataFrame(np.random.randn(6,4),
index=dates, columns=list('ABCD'))
df

                   A         B         C         D
2018-10-01  0.757262 -0.689342 -1.113181 -1.468443
2018-10-02 -0.987600 -1.824431  0.458333 -1.281730
2018-10-03 -0.676635 -0.829787 -0.793783 -1.612335
2018-10-04 -0.851818 -0.067240  1.108231  0.728116
2018-10-05 -0.170020  1.998995 -0.695816  0.204399
2018-10-06  0.435677  0.560126  0.626389 -0.487705

In [12]:
df = pd.DataFrame(np.random.randn(3,5),
index=['student1','student2','student3']
, columns=list('ABCDE'))
df

                 A         B         C         D         E
student1 -0.736603 -0.234701  0.349596 -0.727880  0.646457
student2 -0.953442 -0.036230 -0.628113 -0.402606  1.403718
student3 -1.154257 -2.218499 -0.956181  0.376379 -0.357748

In [13]:
df2 = pd.DataFrame(
    {
        'A' : 1.,
        'B' : pd.Timestamp('20181001'),
        'C' : pd.Series(2.5,index=list(range(4)),dtype='float32'),
        'D' : np.array([3] * 4,dtype='int32'),
        'E' : pd.Categorical(["test","train","test","train"]),
        'F' : 'foo' })
df2

     A          B    C  D      E    F
0  1.0 2018-10-01  2.5  3   test  foo
1  1.0 2018-10-01  2.5  3  train  foo
2  1.0 2018-10-01  2.5  3   test  foo
3  1.0 2018-10-01  2.5  3  train  foo

In [14]:
df3 = pd.DataFrame(
    [{'A':1.0, 'B': pd.Timestamp('20181001'), 'C':2.5, 'D': 3, 'E': 'test', 'F': 'fod'}])
df3

     A          B    C  D     E    F
0  1.0 2018-10-01  2.5  3  test  fod